services:
  node:
    container_name: discord_bot_dashboard
    build: .
    ports:
      - 8080:2278
    volumes:
      - ./bots:/src/bots
      - ./database:/src/database
    restart: unless-stopped