# zerops.yml

version: '1.0'


services:
  - hostname: nodejs0
    type: nodejs@22

  app:
    image: test1
    ports:
      - "80:80"
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - ./data:/data

  nodejs0:
    image: node:14
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs-app:/usr/src/app

# ... puedes agregar más servicios según sea necesario ...
