# zerops.yml

version: '1.0'

services:
  app:
    image: test1
    ports:
      - "80:80"
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - ./data:/data

# ... puedes agregar más servicios según sea necesario ...
