# zerops.yml

version: '1.0'

services:
  nodejs0:  # Nombre del servicio
    image: node:14  # Cambia esto según la versión de Node.js que necesites
    ports:
      - "3000:3000"  # Cambia el puerto según sea necesario
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs-app:/usr/src/app  # Cambia la ruta según tu estructura de proyecto
    command: ["npm", "start"]  # Comando para iniciar la aplicación

# ... puedes agregar más servicios según sea necesario ...
